Create TLC modal
TempleDAO/temple pull request #825
Opened 2023-06-30 18:00 UTC by nichosystem

# Description
What does this PR solve?

Fixes # (issue)

# Checklist
- [ ] Code follows the style guide
- [ ] I have performed a self-review of my own code
- [ ] New and existing tests pass locally
- [ ] This PR is targeting the correct branch

2023-07-10 22:19 UTC, nichosystem commented
Deploy preview for _core_ ready!

✅ Preview
https://core-arr440zc7-templedao.vercel.app
https://pr-825-preview.templedao.link

Built with commit 48acfaccc5aa144200a99bb9f43c728eb052095c.
This pull request is being automatically deployed with [vercel-action](https://github.com/marketplace/actions/vercel-action)

2023-09-06 14:31 UTC, marshall2112 requested changes
A couple small questions. Manually tested everything in the new modal it works as expected.

2023-09-06 14:52 UTC, nichosystem commented on apps/dapp/src/constants/env/preview.tsx
> +    usdc: '',
balancer wasn't available on testnet for a while but they did recently deploy to sepolia; so for now we're alright as it's status quo to not test swaps on testnet atm, but I will add it to the todo to support balancer sepolia in the future

2023-09-06 14:53 UTC, nichosystem commented on apps/dapp/src/components/Pages/Core/NewUI/TLC/Borrow.tsx
> +          <a href="#">Find out more</a>
yeah, we don't have TLC documentation written atm though. I'll comment this out for now

2023-09-06 15:12 UTC, marshall2112 approved these changes
LGTM

2023-09-06 15:17 UTC, merged