Geoblocker
TempleDAO/temple pull request #833
Opened 2023-07-13 17:17 UTC by nichosystem

# Description
What does this PR solve?

Fixes # (issue)

# Checklist
- [ ] Code follows the style guide
- [ ] I have performed a self-review of my own code
- [ ] New and existing tests pass locally
- [ ] This PR is targeting the correct branch

2023-07-14 19:32 UTC, nichosystem commented
Deploy preview for _core_ ready!

✅ Preview
https://core-h0d9p2wcr-templedao.vercel.app
https://pr-833-preview.templedao.link

Built with commit 4010b4b6f273e951368c32762ef25080fdda114e.
This pull request is being automatically deployed with [vercel-action](https://github.com/marketplace/actions/vercel-action)

2023-07-18 18:04 UTC, marshall2112 requested changes
I have two small pieces of feedback (nits, not blocking) and a question.

2023-07-18 18:04 UTC, marshall2112 commented on apps/dapp/src/components/Layouts/CoreLayout/Account.tsx
> +    return <ConnectButton disabled={true} label="Restricted Jurisdiction" isSmall isActive isUppercase role="button" />;
Nit: prefer to omit explicit `true`, i.e. `<ConnectButton disabled label=....`

2023-07-18 18:20 UTC, nichosystem commented on apps/dapp/api/geoblock.js
> +    blocked: ['US', 'CN', 'RU', 'KP', 'IR'].includes(request.headers['x-vercel-ip-country']),
let's skip for now and revisit if it becomes a painpoint

2023-07-18 18:26 UTC, marshall2112 approved these changes
LGTM

2023-07-18 18:49 UTC, merged