Port TLC and Ohmage to dapp V2
TempleDAO/temple pull request #878
Opened 2023-10-24 16:54 UTC by nichosystem

# Description
What does this PR solve?

Fixes # (issue)

# Checklist
- [ ] Code follows the style guide
- [ ] I have performed a self-review of my own code
- [ ] New and existing tests pass locally
- [ ] This PR is targeting the correct branch

2023-10-24 17:09 UTC, nichosystem commented
Deploy preview for _core_ ready!

✅ Preview
https://core-6ttumfpj3-templedao.vercel.app
https://pr-878-preview.templedao.link

Built with commit de5e92c428cb1f0f60250ec251ca2632c49c4564.
This pull request is being automatically deployed with [vercel-action](https://github.com/marketplace/actions/vercel-action)

2023-10-25 11:54 UTC, marshall2112 requested changes
A few small things but otherwise it all seems to work

2023-10-31 17:12 UTC, nichosystem commented on apps/dapp/src/components/Pages/Core/DappPages/Borrow/TLC/TLCModal.tsx
> +import { TempleLineOfCredit__factory, ERC20__factory, TreasuryReservesVault__factory } from 'types/typechain';
good call, deleted this file

2023-10-31 17:14 UTC, nichosystem commented on apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
> +      'https://api.thegraph.com/subgraphs/name/medariox/v2-mainnet',
fixed!

2023-10-31 17:23 UTC, nichosystem commented on apps/dapp/src/components/Pages/Core/DappPages/OhmagePage.tsx
> +          disabled={!signer || insufficientBalance || insufficientDaiAvailable}
fixed

2023-11-07 18:22 UTC, nichosystem commented on apps/dapp/src/components/Pages/Core/DappPages/Borrow/TLC/Supply.tsx
> +import { Input } from '../../../NewUI/HomeInput';
Hm I'm having a tough time replicating. Will dm, can make it a separate PR for fixing too

2023-11-07 22:39 UTC, merged